#!/bin/sh
# Regenerate the golden `prepare --json` fixture.
#
# The golden is a PRODUCER contract: it must be generated by the binary built
# from this exact checkout, never by an arbitrary `perseus-vault` found on
# PATH — a stale installed binary can silently "validate" an older output
# shape. This script therefore refuses to run without the checkout-built
# release binary at ./target/release/perseus-vault:
#
#   cargo build --release --locked
#   ./integrations/noisegate/regen.sh > integrations/noisegate/prepare_output.golden.json
#
# It seeds a THROWAWAY database with two synthetic entities (no real memory
# data), then captures the deterministic read-only pre-turn output on stdout.
# Output is byte-identical across repeated runs against the unchanged DB
# (prepare is read-only; the recall path that reinforces access/decay is not
# exercised). CI diffs this output against the committed golden.
set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$HERE/../.." && pwd)
BIN="$ROOT/target/release/perseus-vault"

if [ ! -x "$BIN" ]; then
  echo "regen.sh: checkout-built binary not found at $BIN" >&2
  echo "Build it from this exact checkout first:" >&2
  echo "  cargo build --release --locked" >&2
  echo "The golden must come from the checkout-built binary; an arbitrary" >&2
  echo "perseus-vault on PATH can silently be a different version." >&2
  exit 1
fi

# Private temp dir (mktemp -d, not mktemp -u): no predictable shared-temp race.
TMPD=$(mktemp -d "${TMPDIR:-/tmp}/pv-prepare-fixture.XXXXXX")
trap 'rm -rf "$TMPD"' EXIT
DB="$TMPD/fixture.db"

"$BIN" write --db "$DB" --category convention --key commit_discipline \
  --entity-type convention --always-on --importance 0.9 \
  --body '{"content":"Always run the full test suite before committing; never push directly to main."}' >/dev/null

"$BIN" write --db "$DB" --category insight --key auth_tokens \
  --entity-type insight --tags auth,security \
  --body '{"content":"The auth module issues JWT access tokens (15-min TTL) with refresh-token rotation."}' >/dev/null

"$BIN" prepare --json --task "refactor the auth module token handling" --db "$DB"
